# Generated by Django 4.2.1 on 2023-06-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('domainAddress', models.CharField(default='default_domainAddress', max_length=100)),
                ('employeeCount', models.IntegerField(default=0)),
                ('firstName', models.CharField(default='default_firstName', max_length=50)),
                ('lastName', models.CharField(default='default_lastName', max_length=50)),
                ('phone', models.CharField(default='default_phone', max_length=20)),
                ('emailContact', models.EmailField(default='default_emailContact', max_length=100, unique=True)),
                ('businessAddress', models.CharField(default='default_businessAddress', max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
