# Generated by Django 4.2.1 on 2023-06-12 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('user_status', models.CharField(max_length=50)),
                ('admin_role', models.BooleanField(default=False)),
                ('admin_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('department_abbreviation', models.CharField(max_length=10)),
                ('department_id', models.CharField(max_length=10)),
                ('memory_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
