# Generated by Django 4.2.1 on 2023-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='businessAddress',
            field=models.CharField(default='default_businessAddress', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='domainAddress',
            field=models.CharField(default='default_domainAddress', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='emailContact',
            field=models.EmailField(default='default_emailContact', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='employeeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='firstName',
            field=models.CharField(default='default_firstName', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='default_lastName', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='default_phone', max_length=20),
        ),
    ]
