# Generated by Django 4.2.1 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_useraccount_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='database',
        ),
    ]
